name: GlintTest
version: ${project.version}
main: px86.glinttest.GlintTest
api-version: '1.20'
author: px86
description: Simulates fake enchantment glint using particles on diamond armor

commands:
  glintvariation:
    description: Switch the particle glint variation
    usage: /glintvariation <1-4>
    aliases: [gv]
  glinttoggle:
    description: Toggle the glint effect on/off
    usage: /glinttoggle
    aliases: [gt]

permissions:
  glinttest.command:
    description: Allows using glintvariation command
    default: op
  glinttest.toggle:
    description: Allows using glinttoggle command
    default: op
